
import{useState,useEffect,useCallback}from'react';import{h}from'../h';
import{getTasks,getCards,getReviews,addReview,updateItem,getDailyFocusMin,getTodayStr,isToday,calcStreak,KEYS,formatDuration}from'../utils/storage';
export default function DailyReviewPage(props){var today=getTodayStr();var existing=useCallback(function(){return getReviews().find(function(r){return(r.date||r.createdAt||'').split('T')[0]===today})},[today]);
var cs=useState(existing());var review=cs[0];var setReview=cs[1];var ls=useState(review?review.learnings:'');var learnings=ls[0];var setLearnings=ls[1];var ts=useState(review?review.tomorrowPlan:'');var tomorrow=ts[0];var setTomorrow=ts[1];var ss=useState(false);var saved=ss[0];var setSaved=ss[1];var ps=useState([]);var pastReviews=ps[0];var setPastReviews=ps[1];
useEffect(function(){setPastReviews(getReviews().slice(0,10))},[]);
var tasks=getTasks();var todayCompleted=tasks.filter(function(t){return t.completed&&isToday(t.completedAt)}).length;var todayTotal=tasks.filter(function(t){return isToday(t.dueDate)||!t.dueDate}).length;var focusMin=getDailyFocusMin();var cardsReviewed=0;getCards().forEach(function(c){if(c.lastReviewed&&isToday(c.lastReviewed))cardsReviewed++});
var handleSave=function(){var data={date:new Date().toISOString(),focusMinutes:focusMin,tasksCompleted:todayCompleted,tasksTotal:todayTotal,cardsReviewed:cardsReviewed,learnings:learnings,tomorrowPlan:tomorrow};if(review){updateItem(KEYS.REVIEWS,review.id,data)}else{addReview(data)}setSaved(true);props.showToast('Review saved')};
if(saved)return h('div',{style:{textAlign:'center',padding:'var(--space-12)'}},h('div',{style:{fontSize:'3rem',marginBottom:'var(--space-4)'}},'✅'),h('h2',{style:{marginBottom:'var(--space-2)'}},'Review Saved'),h('p',{className:'text-tertiary',style:{marginBottom:'var(--space-6)'}},'Great work today.'),h('button',{className:'btn btn-primary',onClick:function(){setSaved(false)}},'View Review'));
return h('div',null,h('h2',{style:{marginBottom:'var(--space-2)'}},'Daily Review'),h('p',{className:'text-tertiary',style:{marginBottom:'var(--space-6)'}},new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})),h('div',{className:'review-stats'},[{v:formatDuration(focusMin),l:'Focus Time'},{v:todayCompleted+'/'+todayTotal,l:'Tasks Done'},{v:cardsReviewed,l:'Cards Reviewed'},{v:calcStreak()+' days',l:'Streak',c:'var(--accent-text)'}].map(function(s,i){return h('div',{className:'review-stat-item',key:i},h('div',{className:'rs-val',style:{color:s.c||'var(--text-primary)'}},s.v),h('div',{className:'rs-lbl'},s.l))})),h('div',{className:'form-group',style:{marginTop:'var(--space-6)'}},h('label',null,'What did I learn today?'),h('textarea',{className:'textarea',placeholder:'Key takeaways, concepts, insights...',value:learnings,onChange:function(e){setLearnings(e.target.value)},rows:4})),h('div',{className:'form-group'},h('label',null,'What should I do tomorrow?'),h('textarea',{className:'textarea',placeholder:'Top priorities for tomorrow...',value:tomorrow,onChange:function(e){setTomorrow(e.target.value)},rows:3})),h('button',{className:'btn btn-primary btn-block',style:{marginTop:'var(--space-4)'},onClick:handleSave},'Save Review'),pastReviews.length>0&&h('div',{style:{marginTop:'var(--space-10)'}},h('div',{className:'section-label'},'Past Reviews'),pastReviews.map(function(r){return h('div',{key:r.id,className:'card',style:{marginBottom:'var(--space-2)'}},h('div',{style:{display:'flex',justifyContent:'space-between',fontSize:'var(--text-xs)',color:'var(--text-tertiary)',marginBottom:'var(--space-2)'}},h('span',{className:'mono'},new Date(r.date||r.createdAt).toLocaleDateString()),h('span',{className:'mono'},formatDuration(r.focusMinutes)+' focused')),r.learnings&&h('p',{style:{fontSize:'var(--text-sm)',color:'var(--text-secondary)',lineHeight:1.5}},r.learnings))})))}
