
import{useState,useEffect,useCallback}from'react';import{h}from'../h';import{getDueCards,rateCard}from'../utils/storage';
export default function FlashcardPage(props){var cs=useState([]);var cards=cs[0];var setCards=cs[1];var is=useState(0);var idx=is[0];var setIdx=is[1];var rs=useState(false);var revealed=rs[0];var setRevealed=rs[1];var rs2=useState({hard:0,good:0,easy:0});var ratings=rs2[0];var setRatings=rs2[1];var fs=useState(false);var finished=fs[0];var setFinished=fs[1];
useEffect(function(){var due=getDueCards();if(due.length===0){setFinished(true);return}setCards(due);setIdx(0);setRevealed(false);setRatings({hard:0,good:0,easy:0});setFinished(false)},[]);
var handleRate=function(rating){var card=cards[idx];rateCard(card,rating);var nr=Object.assign({},ratings);nr[rating]++;setRatings(nr);if(idx+1>=cards.length){setFinished(true)}else{setIdx(idx+1);setRevealed(false)}};
var total=cards.length;var card=cards[idx];
if(finished){var totalR=ratings.hard+ratings.good+ratings.easy;var acc=totalR>0?Math.round((ratings.good+ratings.easy)/totalR*100):0;return h('div',{className:'session-summary'},h('div',{className:'session-summary-card'},h('h2',null,'Session Complete'),h('div',{className:'sum-row'},h('span',null,'Reviewed'),h('span',{className:'mono'},totalR)),h('div',{className:'sum-row'},h('span',{className:'text-danger'},'Hard'),h('span',{className:'mono text-danger'},ratings.hard)),h('div',{className:'sum-row'},h('span',{className:'text-success'},'Good'),h('span',{className:'mono text-success'},ratings.good)),h('div',{className:'sum-row'},h('span',{className:'text-accent'},'Easy'),h('span',{className:'mono text-accent'},ratings.easy)),h('div',{className:'sum-row'},h('span',null,'Accuracy'),h('span',{className:'mono',style:{color:acc>=80?'var(--success)':acc>=50?'var(--warning)':'var(--danger)'}},acc+'%')),h('button',{className:'btn btn-primary btn-block',style:{marginTop:'var(--space-6)'},onClick:props.onDone},'Back to Cards')))}
if(!card)return h('div',{className:'flashcard-container'},h('p',{className:'text-tertiary'},'No cards due for review.'));
var circumference=2*Math.PI*90;var kp=card.keyPoints?card.keyPoints.split('\n').filter(function(l){return l.trim()}):[];
return h('div',{className:'flashcard-container'},h('div',{className:'flashcard-progress'},h('span',{className:'mono'},(idx+1)+' / '+total)),h('button',{className:'btn btn-ghost flashcard-exit',onClick:props.onDone},'Exit'),h('div',{className:'flashcard-content'},card.subject&&h('div',{className:'flashcard-subject'},card.subject),h('div',{className:'flashcard-question'},card.question),!revealed?h('button',{className:'btn btn-primary btn-lg',onClick:function(){setRevealed(true)}},'Reveal Answer'):h('div',null,h('div',{className:'flashcard-answer visible'},card.answer),card.formula&&h('div',{className:'flashcard-formula'},card.formula),kp.length>0&&h('div',{className:'flashcard-keypoints'},kp.map(function(point,i){return h('div',{key:i},h('strong','• '),point)})),h('div',{className:'flashcard-actions'},h('button',{className:'rating-btn rating-hard',onClick:function(){handleRate('hard')}},'Hard'),h('button',{className:'rating-btn rating-good',onClick:function(){handleRate('good')}},'Good'),h('button',{className:'rating-btn rating-easy',onClick:function(){handleRate('easy')}},'Easy')))))}
