import{useState,useCallback,useEffect,useRef}from'react';import{h}from'./h';import{useApp}from'./context/AppContext';import{getTasks,getCards,getNotes,getProjects}from'./utils/storage';
import Sidebar from'./components/Sidebar';import MobileNav from'./components/MobileNav';
import Dashboard from'./pages/Dashboard';import Tasks from'./pages/Tasks';import Cards from'./pages/Cards';
import Flashcard from'./pages/Flashcard';import Pomodoro from'./pages/Pomodoro';
import Notes from'./pages/Notes';import Projects from'./pages/Projects';
import Statistics from'./pages/Statistics';import DailyReview from'./pages/DailyReview';
import Settings from'./pages/Settings';import PDFLibrary from'./pages/PDFLibrary';import'./App.css';import'./features.css';
var searchSvg=h('svg',{viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:'2',strokeLinecap:'round',strokeLinejoin:'round'},h('circle',{cx:'11',cy:'11',r:'8'}),h('line',{x1:'21',y1:'21',x2:'16.65',y2:'16.65'}));
var xSvg=h('svg',{width:'18',height:'18',viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:'2',strokeLinecap:'round'},h('line',{x1:'18',y1:'6',x2:'6',y2:'18'}),h('line',{x1:'6',y1:'6',x2:'18',y2:'18'}));
function doSearch(q){var ql=q.toLowerCase();var r={tasks:[],cards:[],notes:[],projects:[]};
getTasks().forEach(function(t){if(t.title.toLowerCase().indexOf(ql)>-1||(t.description&&t.description.toLowerCase().indexOf(ql)>-1))r.tasks.push(t)});
getCards().forEach(function(c){var ct=(c.title||'').toLowerCase();var cq=(c.question||'').toLowerCase();if(ct.indexOf(ql)>-1||cq.indexOf(ql)>-1)r.cards.push(c)});
getNotes().forEach(function(n){if(n.title.toLowerCase().indexOf(ql)>-1||(n.content||'').toLowerCase().indexOf(ql)>-1)r.notes.push(n)});
getProjects().forEach(function(p){if(p.name.toLowerCase().indexOf(ql)>-1||(p.description||'').toLowerCase().indexOf(ql)>-1)r.projects.push(p)});
return r}
function SearchModal(props){var s=useState('');var q=s[0];var setQ=s[1];var ref=useRef(null);
var results=useCallback(function(){if(!q.trim())return null;var r=doSearch(q);var total=r.tasks.length+r.cards.length+r.notes.length+r.projects.length;if(total===0)return'empty';return r},[q]);
useEffect(function(){if(props.open){setQ('');setTimeout(function(){if(ref.current)ref.current.querySelector('input').focus()},100)}},[props.open]);
if(!props.open)return null;var res=results();
var groups=[{key:'tasks',label:'Tasks',items:res==='empty'?[]:res.tasks,nav:'tasks'},{key:'cards',label:'Cards',items:res==='empty'?[]:res.cards,nav:'cards'},{key:'notes',label:'Notes',items:res==='empty'?[]:res.notes,nav:'notes'},{key:'projects',label:'Projects',items:res==='empty'?[]:res.projects,nav:'projects'}];
return h('div',{className:'search-overlay',onClick:function(e){if(e.target===e.currentTarget)props.onClose()}},h('div',{className:'search-panel',ref:ref},h('div',{className:'search-input-wrap'},searchSvg,h('input',{type:'text',placeholder:'Search everything...',value:q,onChange:function(e){setQ(e.target.value)}}),h('button',{className:'btn btn-ghost btn-sm',onClick:props.onClose},xSvg)),res==='empty'?h('div',{className:'search-empty'},'No results found'):groups.filter(function(g){return g.items.length>0}).map(function(g){return h('div',{className:'search-group',key:g.key},h('div',{className:'search-group-label'},g.label+' ('+g.items.length+')'),g.items.slice(0,8).map(function(item){return h('div',{className:'search-result',key:item.id,onClick:function(){props.onClose();props.onNavigate(g.nav)}},h('span',{className:'sr-type'},g.label.slice(0,-1)),h('span',{className:'sr-text'},item.title||item.question||item.name))}))})))}
export default function App(){var cs=useState('dashboard');var currentPage=cs[0];var setCurrentPage=cs[1];var os=useState(false);var searchOpen=os[0];var setSearchOpen=os[1];var fs=useState(false);var focusMode=fs[0];var setFocusMode=fs[1];var app=useApp();var toasts=app.toasts;var showToast=app.showToast;
var navigate=useCallback(function(p){setCurrentPage(p);setFocusMode(false);window.scrollTo(0,0)},[]);
useEffect(function(){var handler=function(e){if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA'||e.target.tagName==='SELECT')return;if(e.key==='/'){e.preventDefault();setSearchOpen(true)}if(e.key==='Escape')setSearchOpen(false)};window.addEventListener('keydown',handler);return function(){window.removeEventListener('keydown',handler)}},[]);
var renderPage=function(){switch(currentPage){case'dashboard':return h(Dashboard,{onNavigate:navigate});case'tasks':return h(Tasks,{showToast:showToast});case'cards':return h(Cards,{showToast:showToast,onStartRevision:function(){setCurrentPage('flashcard')}});case'flashcard':return h(Flashcard,{showToast:showToast,onDone:function(){setCurrentPage('cards')}});case'pomodoro':return h(Pomodoro,{showToast:showToast,onEnterFocus:function(){setFocusMode(true)},focusMode:focusMode,onExitFocus:function(){setFocusMode(false)}});case'notes':return h(Notes,{showToast:showToast});case'pdf':return h(PDFLibrary,{showToast:showToast});case'projects':return h(Projects,{showToast:showToast});case'statistics':return h(Statistics,{});case'review':return h(DailyReview,{showToast:showToast});case'settings':return h(Settings,{showToast:showToast});default:return h(Dashboard,{onNavigate:navigate})}};
if(focusMode){return h('div',{className:'app'},h(Pomodoro,{showToast:showToast,focusMode:true,onExitFocus:function(){setFocusMode(false)},onEnterFocus:function(){}}))}
return h('div',{className:'app'},h(Sidebar,{currentPage:currentPage,onNavigate:navigate}),h('header',{className:'mobile-header'},h('h1',null,'THRUST')),h('main',{className:'main-content'},renderPage()),h(MobileNav,{currentPage:currentPage,onNavigate:navigate}),h(SearchModal,{open:searchOpen,onClose:function(){setSearchOpen(false)},onNavigate:navigate}),h('div',{className:'toast-container','aria-live':'polite'},toasts.map(function(t){return h('div',{key:t.id,className:'toast'+(t.exiting?' toast-exit':'')},t.message)})))}
